[package]
name = "axvm"
version = "0.1.0"
edition = "2021"

[features]
default = ["vmx"]
vmx = []

[dependencies]
log = "=0.4.19"
cfg-if = "1.0"
bitflags = "2.2"
bit_field = "0.10"
numeric-enum-macro = "0.2"

# System independent crates provided by ArceOS, these crates could be imported by remote url. 
axerrno = { path = "../../arceos/crates/axerrno" }
spinlock = { path = "../../arceos/crates/spinlock" }
memory_addr = { path = "../../arceos/crates/memory_addr" }
page_table = { path = "../../arceos/crates/page_table" }
page_table_entry = { path = "../../arceos/crates/page_table_entry" }
percpu = { path = "../../arceos/crates/percpu" }

# Operating system dependent modules provided by ArceOS, these modules could be imported by remote url.
axhal = { path = "../../arceos/modules/axhal" }

[target.'cfg(target_arch = "x86_64")'.dependencies]
x86 = "0.52"
x86_64 = "0.14"
raw-cpuid = "11.0"


[target.'cfg(target_arch = "aarch64")'.dependencies]
cortex-a = "8.1.1"
aarch64-cpu = "9.3"
smccc = "0.1.1"